tel: '+16135551999'
tel_display: 613 555 1234
seo:
  tagline: Live the dream in an old-style English Cottage
location:
  country: England
  locality: Leamington Spa
  region: Warwickshire
  street_address: 6 Rue Hôtel de Ville
